### ISSUE TITLE
EADDRINUSE exception when attempting to use

### ISSUE THREAD

**Issue by jfisher446** [juzim/MMM-Api#3]
I receive the below error any time I try to load MM with this module. If I deactivate the loadModules calls within the module, the errors cease, but the functionality is unavailable.

```
0|MagicMirror  | Whoops! There was an uncaught exception... 
0|MagicMirror  | [2020-09-27 00:02:43.442] [ERROR]
0|MagicMirror  | Error: listen EADDRINUSE: address already in use 127.0.0.1:3513
0|MagicMirror  |     at Server.setupListenHandle [as _listen2] (net.js:1226:14)
0|MagicMirror  |     at listenInCluster (net.js:1274:12)
0|MagicMirror  |     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1413:7)
0|MagicMirror  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10) {
0|MagicMirror  |   code: 'EADDRINUSE',
0|MagicMirror  |   errno: 'EADDRINUSE',
0|MagicMirror  |   syscall: 'listen',
0|MagicMirror  |   address: '127.0.0.1',
0|MagicMirror  |   port: 3513
0|MagicMirror  | }
0|MagicMirror  | [2020-09-27 00:02:43.444] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMirror  | [2020-09-27 00:02:43.445] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

**Comment by juli-dot-md** [comment]
It looks like it loads a module twice, I'll try to look into it.
